---
- hosts: default
  name: install devstack
  remote_user: vagrant
  tasks:
    - name: updates a server
      apt: update_cache=yes
      sudo: yes
    # - name: upgrade a server
    #   apt: upgrade=dist
    #   sudo: yes
    - name: ensure git is installed
      apt: pkg=git state=latest
      sudo: yes
    - name: clone devstack
      git: repo=https://github.com/openstack-dev/devstack.git
        dest=/home/vagrant/devstack
    - name: grab local.conf file from gist
      command: wget -O /home/vagrant/devstack/local.conf https://gist.githubusercontent.com/rstarmer/29b54c26b32387b392f2/raw/b10877e6610c1347d832fb147345cac918abada4/local.conf
    - name: Add services
      lineinfile: dest=/home/vagrant/devstack/local.conf line="{{item}}"
      with_items:
        - enable_service s-proxy s-object s-container s-account
        - enable_service heat h-api h-api-cfn h-api-cw h-eng
        - enable_service q-lbaasv2
        - enable_service octavia o-cw o-hk o-hm o-api
        - SWIFT_HASH=66a3d6b56c1f479c8b4e70ab5c2000f5
        - SWIFT_REPLICAS=1
        - SWIFT_DATA_DIR=$DEST/data
        - HOST_IP=10.1.64.11
    - name: run stack.sh
      shell: (cd /home/vagrant/devstack; ./stack.sh)
